name: Build

on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        java_version: [21]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: "zulu"
      - name: Maven cache
        uses: actions/cache@v4
        env:
          cache-name: maven-cache
        with:
          path: ~/.m2
          key: build-${{ env.cache-name }}
      - name: Maven version
        run: mvn --version
      - name: Build with Maven
        env:
          JAVA_VERSION: ${{ matrix.java_version }}
        run: |
          mvn clean install -DskipTests -Ptest && mvn clean package -Ptest -DskipTests artifact:compare && mkdir ./target/core && mkdir ./target/compare && cd ./target/core && jar xvf ../../http-generator-core/target/avaje-http-generator-core-2.8-RC5.jar && cd ../compare && ls ../reference/io.avaje && jar xvf ../reference/io.avaje/avaje-http-generator-core-2.8-RC5.jar && cd .. && diff -r core compare

